create database payroll_services;
show databases;
use payroll_services;
Create Table employee_payroll(id int unsigned not null auto_increment,name varchar(100)not null,salary double not null,start date not null,primary key (id));
show tables;
insert into employee_payroll(name,salary,start) values ("Bill",1000000.00,"2018-01-03"),("Mark",2000000.00,"2019-11-13"),("Charly",3000000.00,"2020-05-21");
select * from employee_payroll;
select salary from employee_payroll where name = "Bill";
select * from employee_payroll WHERE start BETWEEN CAST('2018-01-01'AS DATE) AND DATE(NOW());
alter table employee_payroll add gender char(1) after name; 
update employee_payroll set gender = "M" where id = 1 or id = 3;
update employee_payroll set gender = "F" where id = 2; 
SELECT SUM(salary) FROM employee_payroll WHERE gender = 'M' GROUP BY gender;
SELECT avg(salary) FROM employee_payroll WHERE gender = 'M' GROUP BY gender;
SELECT min(salary) FROM employee_payroll WHERE gender = 'M' GROUP BY gender;
SELECT max(salary) FROM employee_payroll WHERE gender = 'M' GROUP BY gender;
SELECT count(salary) FROM employee_payroll WHERE gender = 'M' GROUP BY gender;
alter table employee_payroll add employee_phone int  after start; 
alter table employee_payroll add address varchar(100) after employee_phone; 
alter table employee_payroll add department varchar(100)not null after address; 
alter table employee_payroll add basic_pay double after department; 
alter table employee_payroll add deductions double after basic_pay; 
alter table employee_payroll add taxable_pay double after deductions; 
alter table employee_payroll add income_tax double after taxable_pay; 
alter table employee_payroll add net_pay double after income_tax; 
select name from employee_payroll where salary in (3000000,1000000);